# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Loving' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Loving
pod 'RxSwift', '~> 3.4.0'
pod 'RxCocoa', '~> 3.4.0'
pod 'Alamofire', '~> 4.4.0'
pod 'AlamofireImage', '~> 3.2.0'
pod 'SVProgressHUD', '~> 2.1.2'

end
